### PR TITLE
Update Resources.fr.resx

### PR DESCRIPTION
**Pull request by seboudry**
Hi!
My little contribution for this awesome software ;)

### CODE REVIEW

**Comment by rocksdanister** [comment]
Hi, it looks like there are quite a few changes to existing texts which are already translated by @pekatour and @Lulucmy 
May I know what is the main changes you made since I don't know French myself.

**Comment by seboudry** [comment]
Most of modifications is on "settings" screen, some harmonization among texts for a better understanding.
Also some spelling and punctuation corrections.
If they are some french people that can review my modifications, it would be even better ;)

**Comment by Lulucmy** [comment]
Sounds good to me :)

**Comment by pekatour** [comment]
Generally seems good to me, only at line 419, doit*
Apart from that it all seems good. Good job!

**Comment by seboudry** [comment]
Nice catch!
Fixed

**Pull request merged**
