### PR TITLE
Fix Vietnamese's word use depend on context,   add Japanese translati…

### PR DESCRIPTION
**Pull request by ShaneVu**
Fix Vietnamese's word use depend on context
Add japanese translation resource(on progress)

### CODE REVIEW

**Comment by rocksdanister** [comment]
Add language tag to filename
https://github.com/rocksdanister/lively-translations/blob/master/README.md

**Comment by ShaneVu** [comment]
Sorry,  language tag is added.

**Comment by rocksdanister** [comment]
japanese also 😅

**Comment by ShaneVu** [comment]
I am really sorry! First time contributing... 
I will commit this Vietnamese translation first. The Japanese translation part is still on progress, I will finish and test this Japanese part (check misspell, word context ...) before making another pull request.

**Comment by rocksdanister** [comment]
No worries 🤗

**Pull request merged**
